[build]
  functions = "functions"

[dev]
  functions = "functions"
  publish = "public"

# Simple redirect to make sure index.html is served at the root
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
