[build]
  functions = "functions"

[dev]
  functions = "functions"
  publish = "public"

# Redirect /api to the registry function
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/registry"
  status = 200
